# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f77b2c9f7e4f246eb57b65817cd6c780e38af0c25b4f3736aa76e9ac64c031c302a8d962d728a1fd9e975be07f5220bbbfee50300f63dfca68b7bdc8c024743

test:
  secret_key_base: 56eb1d4c3f77f3561ca957d85e872985cc99c11b226187755fe2d471edcabfc624ff3c6a7a82817efbb1db8f890989d3eb74073458557ef3e59b1f58421e3b2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
